export const FX_SYMBOLS = ["BTCUSD", "XAUUSD", "EURUSD", "USDJPY", "GBPJPY"];

export const DERIV_SYMBOLS = [
  "STEP INDEX",
  "VOLATILITY 10 INDEX",
  "VOLATILITY 25 INDEX",
  "VOLATILITY 75 INDEX",
  "VOLATILITY 75 (1S) INDEX",
  "VOLATILITY 100 INDEX",
  "CRASH 500 INDEX",
  "CRASH 1000 INDEX",
];

export const ALL_SYMBOLS = [...FX_SYMBOLS, ...DERIV_SYMBOLS];
